spring.application.name=bankapp

# PostgreSQL Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/fake_bank_of_india
spring.datasource.username=postgres
spring.datasource.password=Password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Email configuration --> For Sending Email OTPs
# Gmail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mybankingapplicationsoftware@gmail.com
spring.mail.password=ioufbtekjijztgvp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# SMS configuration --> For Sending SMS OTPs
twilio.account.sid=YOUR_TWILIO_SID
twilio.auth.token=YOUR_TWILIO_TOKEN
twilio.phone.number=+18103743327